[package]
name = "simple-animgraph"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.102"
glam = "0.32.0"
mapgraph = "0.12.0"
ozz-animation-rs = "0.11.0"
safe_index = "0.10.0"
web-time = "1.1.0"
