[package]
name = "simple-animgraph"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.102"
glam = "0.30.0"
mapgraph = { version = "0.12.0", features = ["algorithms"] }
ozz-animation-rs = "0.11.0"
safe_index = "0.10.0"
web-time = "1.1.0"
